### ISSUE TITLE
Suggestion For Legendary Spawns

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Suggestions#107]
Hi, i would like to request something that could be disappointing to hear, but makes a lil sense when you listen it all. Everyone knows legendaries are a main point of the pixelmon for everyone, but this times in nebula are focues on the pokedex completing system, especially for ppl to get origin rank. Really a lot of people are at master rank now, but there are even the lower ranks. And for a master that is probably only waiting for legendaries to spawn to go through the pokedex, it's pretty disappointing to see a random legendary spawn on a low, really low rank, that maybe just joined the server, and since the moment that gyms aren't still in the server, legendaries are useful just for the pokedex, and who really needs them are luxury+ ranks, don't wanna say that low ranks don't deserve legendary pokemon, but someone really need them, i mean, people around ultra rank have like 500+ pokemons to catch, and uppers just sit in the game to hope they could get a legendary, even because quests aren't still here and won't be for we don't know how much, what about adding some system that gives priority to some ranks instead of others? not a big difference between everyone, but just fair game

**Comment by CenizaRey** [comment]
What you described isn't fair game at all, I'm afraid. Quite the opposite. Even if there was a way to do this, it would be a grossly unattractive feature for new players. I can confidently say lots of people hunt legendaries just to have legendaries, while a minority goes systematically down the list just to fill dex pages.

I cannot imagine saying to a Premier Rank, or even an Ultra Rank, that their chances of their favourite legendary spawning on them have been reduced simply because their pokedex isn't full enough. Which, by the way, is an entirely optional mechanic that people should be able to not take part in and still get the Full Nebula Experience. Adding this feature would be forcing many individuals into a playstyle that may not appeal to them. For those reasons, this will never be implemented. Thank you for the suggestion!
