### ISSUE TITLE
Little Suggestion List

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Suggestions#130]
Hi, i'm here to do a kind of list filled with suggestion to do a single post and not many, so let's start.
1)Vanha events and loot table : 
 Since the map release we had just the gyms, which i mean are pretty good, but i think that a map of that dimensions and such cool could be used fot better things, like what the staff would think about a man/treasure hunt inside the adventure map? in my opinion would be a pretty cool thing. For the same motivation i would ask staff if it may be possible to have some loot things in vanha, but i think that there is already an idea with the pokestops so will just end that here.

2)Server's roadmap:
I don't know if that has ever been thought but what about adding on the discord a channel with some posts or maybe a photo where all the future ideas for the server are? Like no eta or dates, just the concepts to keep the community hyped.

3)Better rewards for dexrewards:
Would like to suggest an increase of prizes for some of the dexranks, especially the origin kit that, in my opinion is worth less than the beast, so could be like some useful items or maybe also cosmetic/megastone/solar / keys be added to the origin kit? or maybe even a chisel for decoration would be so cool in my opinion, but knowing it's a bit too hard so staff decides.

4)New Loot table for world expansion:
That is for a really long long future, or at least i think, this is about loot tables in an eventual overworld/end/nether expansion and also for ultra space, so, the concept is based on what loot every dimension could offer, also considering that the normal loot like bells and things that were already in first world chests are like worth nothing now, so what about changing the loot tables with new items and also based on the dimension? like nether could give fire/dark/ghost gems/memories and things like that, same for the end and other dimensions.

5)Park Rank:
Now that some players have reached the origin rank, i think it would be even more challenging to get a 100%, and why not honoring the park ball with a properly rank? i don't really know the rewards for the one time and weekly kit, but i think that a 100% rank would be maybe motivation of playing more. Also some of the suggestion of the origin rank i did before could be used there: Since we are talking about  a 1% increase, maybe giving a chiesel there or something just to flex, without real prizes that i think a 100% player would not even use.

6)Eternal Flower Floette:
That's pretty a secondary suggestion compared to the others, so would like ask staff to please add that floette's form in form mod or at least letting players get it with some events/lore thing, because it's not even a battle form and also not op as like battle bond greninja or eternamax eternatus are.

7)Last Hope:
That's my last time asking that since i think i gave nausea to cen for how many times i asked, so if i got refused once again i promise i will stop lol. I would like to ask staff to have a sheet of minimum prices for the server, i know it's a really hard and mostly impossible thing to do, but i think that would bring much more stability between each server and also would give some health to server's economy.

Thanks for all the attention yall gave to the post and for everything you'll do :D

**Comment by PenginKami** [comment]
For 1, usually we have snr's for that where you find hidden pokemon around the towns for rewards, I'm unsure where its been as of recent... Would be nice to have it more often, also I may be remembering wrong here but aren't there pokeloots all around the vanha map?

for 2, I believe the nitro only accessible channel *should* have way more sneak peeks and lets you see stuff wayy in advance, but im not in it these days so I cant confirm if it's been posted in as of recent

for 3, cosmetic keys sound lit as an addition to the rewards

for 6, I believe its a palette thats available and really rarely obtained using the sweet scent external move in a flower forest, though if the palette isn't available in 1.16 using that method It'd be nice to have it. though I'm unsure if it gets its signature move and its actual baste stats so it'd be nice if it did (the signature move being light of ruin, and stats are listed here https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_X_and_Y_beta#Eternal_Flower_Floette) 
![image](https://user-images.githubusercontent.com/96862959/195959962-264f25fc-712b-4a35-8bf2-3424ae128c55.png)


for 7, if you mean an online sheet where you can see all the npcs and what they sell for how much, that'd be great.
I was always using the town wiki pages for oblique to figure out where the hell to get certain tms and tutor moves especially lol
but even for just the normal NPCs it would be good.

**Comment by CenizaRey** [comment]
Your list of suggestions contains a lot of good ideas, some of which have already been semi-realised one way or another. Events are beginning to occur more and more on the adventure map, such as the treasure/head hunts you described. We have added a sneak peeks channel for non-nitro boosters to get a little taste of the information Nitro Boosters receive on a regular basis. 

Unfortunately Pixelmon doesn't currently allow us to change pokeloot contents between dimensions. Although in the event it becomes possible, we would very likely also fulfil this suggestion.

I feel bloating dexrewards with yet another rank is unnecessary, considering there's very little we can award that would be worth it beyond the Shiny Charm. Some may choose to Prestige after they reach Origin. I personally don't view grinding to acquire the final percentage of the pokedex as particularly fun. Although this opinion may change later down the line if the idea proves popular in the future.

I wasn't aware AZ's Floette wasn't spawning until now. It now spawns in Flowery Biomes during the day with 0.1 rarity. Thanks for the suggestion! 

And finally, we don't believe in setting minimum prices. The needs of the economy will change over time, even if we do so, and the prices will have to be constantly altered and maintained in order to keep up with these shifts. Eventually, it'll end up so there might as well not even be a minimum price list, as it will have to keep up with the economy, and not the other way around. It is also virtually unenforceable for "under the table" deals that don't go through the GTS or other server-dependent trading routes.

With all that said, this was a good list! Closing for now.
