### ISSUE TITLE
New Alpha pokemons suggestion

### ISSUE THREAD

**Issue by MoloCreator** [NebulaMC-GG/Suggestions#146]
Most of the Alpha mon additional moves are boring, so there's my little list with useful moves that suits them. Serperior, Hawlucha and Basculegion can be too OP

Serperior - Fleur Cannon
Hawlucha - Bolt Beak
Basculegion - Fishious Rend
Bisharp - Behemoth Blade
Snorlax - Drum Beating (STAB with custom mega evo)
Hisui Decidueye - Thousands Arrows
Sharpedo - Jaw Lock
Sceptile - Tail Glow
Spiritomb - Spirit Break
Gengar - Freezing Glare
Empoleon - King's Shield
Grimmsnarl - Topsy-Turvy

**Comment by CenizaRey** [comment]
The goal of Alpha pokemon wasn’t to make the pokemon “stronger”. It was to add a little extra flavour to a few species so that they can be used in different ways than normal. 

For example, we gave Volcarona ‘Leaf Storm’ because we thought that even though it may not always be as good as Giga Drain, it could make it interesting to have a higher power move instead, that could turn the tide of the battle.

We made an effort to make sure these Alphas would remain legal in gyms, but some of your suggestions here, like giving Bisharp ‘Behemoth Blade’ just makes it incredibly strong, and makes Alpha Bisharp simply better than regular. There would be no reason to run ordinary Bisharp if we added that, and that isn’t what Alphas are all about.

Leaving open for now in case you have anything to add

**Comment by PenginKami** [comment]
I like spiritomb's and empoleons personally.
Though with what cen has said, empoleons makes it straight up better than instead of a sidegrade so maybe not (I think thats the term?)

**Comment by MoloCreator** [comment]
Behemoth Blade it's better but not OP, u don't have dynamax mons in gyms so its 100p instead of 80p and 30% for flinch. And I know the goal isn't to make them much better, look at gengar, instead of psychic u can have move with same power but 10% for freeze instead of lowering Sp.Def I think, same with sharpedo, and if u don't want to make Alpha mons stronger, then why there's dynamax cannon Hydreigon or Freeze-dry Milotic. But ye, it's just sugestion, no need to do anything about those mons if u don't want

**Comment by CenizaRey** [comment]
Dynamax cannon isn't better than Draco Meteor, and Freeze-Dry arguably isn't better than scald. I understand the difference between Iron Head and Behemoth Blade may seem small, but it makes a world of difference, as is shown in the calcs below:
![bisharp1](https://user-images.githubusercontent.com/42212238/202560947-937433db-31a9-49e3-8a0b-46412ef5c948.png)
![bisharp2](https://user-images.githubusercontent.com/42212238/202560956-77bbe218-ea82-4362-a0ef-ab691aef5eb2.png)

Closing for now.
