### ISSUE TITLE
Mewtwo price should be reduced 

### ISSUE THREAD

**Issue by Goeategg** [NebulaMC-GG/Suggestions#160]
I think the price to clone a mewtwo should be reduced because you have to find and catch a mew or buy one from someone else and they are not cheap I think it should be reduced to something like 90k or 100k

**Comment by CenizaRey** [comment]
The price of Mewtwo is so high because each Mew can produce a Mewtwo three times. This means that whenever a new wild Mew is caught, the economy treats it as potentially 4 new legendary pokemon. The Mew, plus its three potential offspring. The steep price of the Cloning Machine counteracts this impact on the value of Mewtwo as a pokemon, and keeps legendaries legendary. Closing for now
