### ISSUE TITLE
In game wiki

### ISSUE THREAD

**Issue by Centuron** [NebulaMC-GG/Suggestions#176]
Would it be possible to have the in game show us what evs a particular pokemon will drop?
Since that was a stat that you used to be able to look up.
If not that then would it be possible to have a label near the pokemon spawners at Spawn that say which evs are dropping from each pokemon there?

**Comment by CenizaRey** [comment]
Whenever the EV spawners in Spawn are changed due to an event, they are always replaced with pokemon that give out the same EVs as default. The patterns and locations never change. /wiki no longer giving out information regarding EVs was a Pixelmon change, and cannot be altered by us. Thanks for the suggestion! Closing.
