### ISSUE TITLE
Cobblemon Texture pack for Nebula custom pokemon

### ISSUE THREAD

**Issue by Mattahhb** [NebulaMC-GG/Suggestions#212]
I heard the cobblemon mod was making huge impact. So maybe in the future someone would make a cobblemon texture pack por Pixelmon.

As in the first mods of Pixelmon, the models were cubical, like Minecraft style. 

So ... If that texture pack is created. An texture pack for the custom pokes of the server could be incredible.

It LL be nostalgic to see that style on the Pixelmon Nebula server :)

**Comment by Rasgnarok** [comment]
We've personally got no interest in using BB models especially since we invest more in faithful, quality regionals and forms of the existing Pixelmon dex. While I wouldn't particularly say people will like seeing a blocky Giratina Origin or the likes, they could absolutely make a datapack and add those in for personal use. Just not something we would personally do.
