### ISSUE TITLE
Battle Tower

### ISSUE THREAD

**Issue by 2534u89h** [NebulaMC-GG/Suggestions#215]
Server: Titan

Hello Dev team,

Following the recent changes to the battle tower, I have some suggestions to make that I feel would make the game more enjoyable to a certain group of people without disrupting the enjoyment of other players.
First, we all know battle tower always paid too much without any cooldown which was the main issue. But with the current cooldown changes and the reduction of rewards, it disallowed players who wouldn't have as much time compared to others to find ultra rare pokemon on the bingo to grind money. While I do understand that the whole point of nerfing battle tower is that there is supposed to be a challenge when grinding money so as to combat the recent inflation problem happening across all the servers. But with the 2 hour cooldown in mind, it impacts people that only do battletower as their source of income, as compared to bingos and hunts, they do not take a lengthy amount of time. 
Secondly, with the 2 hour cooldowns, it causes battle tower to now have a smaller margin of error, where if someone that doesn't have a very good team would not be able to progress far and only able to earn 1.2k? It's crazy.
Thirdly, In order to even finish the battle tower, you of course would need to have a decent enough team. With this in mind, you would need to invest money into buying mons, mods and even some items for your pokemon to hold.
So with all these implications in mind, here are some changes I suggest-
A) Cooldown for Battletower to be removed. ( with rewards reduction). With the issue of the battletower constantly freezing at tower floors, it is also unfair for the people that encounter it consistently. Prices of items now are too expensive as newer players with not much money are unable to purchase mods or items to put on mons. Eventually, people that do battletower due to time constraints are not going to have enough money. 
B) Only introduce cooldowns to people that finish the battletower.
C) Increase the end rewards for finishing the tower, as a measly 20k wouldnt suffice for the cost of the teams required to beat BT

Cheers

**Comment by CenizaRey** [comment]
Let’s tackle this item by item:

1. The issue of the waiting glitches in Pixelmon has never been closer to being solved. As of the next Pixelmon update, a huge amount of battle errors which cause waiting glitches will have been fixed, drastically reducing the chances of challenges ending prematurely due to reasons outside of the user’s control. 

2. This sounds like a good idea, but would ultimately lead to exploitation wherein teams would be built to be optimised against a specific NPC typing to counter and defeat it as fast as possible, leading to a cooldown-less flow of cash to the user.

3. The goal of Battle Tower is not to help users break even. No matter how much the average comp team costs, and how long it took to build, just 12 hours of back-to-back completed runs of the Battle Tower, that’s 6 runs; will yield 255k. This should more than cover any reasonable team, I wouldn’t at all describe it as measley.

I appreciate the nerfing of Battle Tower was severe and sudden, but understand that the old way rewards were DEEPLY overpowered, and that the new restrictions are only underpowered by comparison, not underpowered in and of themselves. 

Ultimately, it is almost 50k for just battling in a pressure-free environment against a set of NPCs. With decent strategy and teambuilding, we do not view the Battle Tower as entirely difficult.
