### ISSUE TITLE
[Suggestion] Enhance the Not OT Breeding Protection

### ISSUE THREAD

**Issue by BunkerMonk** [NebulaMC-GG/Suggestions#59]
At the moment if you are not the OT and you try to breed for a Hidden Ability, you get an error message and the pokemon will not pass the ability onto its children. May I suggest that this protection be extended to also include natures and IVs? 

Natures might be able to be done by having any pokemon born with a Non-OT parent default to being a Hardy Nature.
Ivs can be done by making them default to like 10 or something.

These changes would still allow for people to species trade and ball trade mons, but they would make it even safer for the econ in case someone forgets to unbreed. Or might just eliminate the need to unbreed at all.

**Comment by CenizaRey** [comment]
This is the entire point of the /unbreed command. I really don’t feel as though this is at all necessary. People should be able to sell male breeding partners for use in breeding other members of that egg group. Otherwise, breeding is limited entirely to the individual, and leaves no opportunity for collaborating teams.
