### ISSUE TITLE
Increase the blocks needed between elevators

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#90]
The actual maximum blocks needed for elevators to works, even is kinda a good space, if ur making something bigger or ur building have a really big space, the space between them turned not enough to work limiting the opportunity to play in your buildings with that. 

The elevator is a cheap block that only works for that and delete other type of vainila elevators cause is much more helpful, something cool, but i don't think should have a restriction like that (the new elevators made of kelp doesn't have that restriction and they are not expensive). So i think elevators space should be highly increased the maximum blocks needed between them to let players play more in his buildings. 

I can undestand if that is a issue because they are cheap, make a new custom recipe more expensive to balance it, but i don't think is necessary.

**Comment by fatyg5** [comment]
This was 25 when I looked recently, but I have increased it to 32. We'll see if we can get more information on if going higher would cause any issues, as I don't want to run into performance issues due to it having to check 32 blocks below every time someone uses an elevator, as there's a possibility that could bring lag.

32 blocks should be a substantial number for now, and as I said we'll see about increasing after we receive input on it. 

Thank you for the suggestion!
